import React from 'react';
import { Logo } from '../ui/Logo';
import { AlertCircle } from 'lucide-react';

export const Footer: React.FC = () => {
  return (
    <footer className="bg-slate-900 text-slate-400 border-t border-slate-800 pt-12 pb-8">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8 pb-10 border-b border-slate-800">
          {/* Brand Info */}
          <div className="md:col-span-1 space-y-4">
            <Logo size="md" showTagline />
            <p className="text-xs text-slate-400 leading-relaxed">
              AI-Powered ingredient label OCR extraction, allergen identification, and personalized hazard safety analysis.
            </p>
          </div>

          {/* Quick Links */}
          <div>
            <h5 className="text-xs font-bold uppercase tracking-wider text-slate-200 mb-3">Navigation</h5>
            <ul className="space-y-2 text-xs">
              <li><a href="/" className="hover:text-teal-400 transition-colors">Home</a></li>
              <li><a href="#how-it-works" className="hover:text-teal-400 transition-colors">How It Works</a></li>
              <li><a href="#features" className="hover:text-teal-400 transition-colors">Features</a></li>
              <li><a href="#why-labelcheck" className="hover:text-teal-400 transition-colors">Why LabelCheck</a></li>
            </ul>
          </div>

          {/* Application Features */}
          <div>
            <h5 className="text-xs font-bold uppercase tracking-wider text-slate-200 mb-3">Product</h5>
            <ul className="space-y-2 text-xs">
              <li><a href="/scan" className="hover:text-teal-400 transition-colors">Scan Product Label</a></li>
              <li><a href="/history" className="hover:text-teal-400 transition-colors">Scan History</a></li>
              <li><a href="/saved" className="hover:text-teal-400 transition-colors">Saved Products</a></li>
              <li><a href="/compare" className="hover:text-teal-400 transition-colors">Product Comparison</a></li>
            </ul>
          </div>

          {/* Legal / Contact */}
          <div>
            <h5 className="text-xs font-bold uppercase tracking-wider text-slate-200 mb-3">Legal & Support</h5>
            <ul className="space-y-2 text-xs">
              <li><a href="#" className="hover:text-teal-400 transition-colors">Privacy Policy</a></li>
              <li><a href="#" className="hover:text-teal-400 transition-colors">Terms of Service</a></li>
              <li><a href="#" className="hover:text-teal-400 transition-colors">Contact Support</a></li>
              <li><a href="#" className="hover:text-teal-400 transition-colors">Minor Project Synopsis</a></li>
            </ul>
          </div>
        </div>

        {/* Medical & Informational Disclaimer */}
        <div className="mt-8 p-4 bg-slate-950/80 rounded-2xl border border-slate-800 flex items-start gap-3">
          <AlertCircle className="w-5 h-5 text-amber-500 shrink-0 mt-0.5" />
          <div className="text-[11px] text-slate-400 leading-relaxed">
            <span className="font-bold text-slate-200">Informational Risk Guidance Disclaimer: </span>
            LabelCheck provides ingredient hazard and allergen analysis for general informational and educational purposes only. Safety scores (0–100) are non-regulatory risk estimations generated by AI algorithms and public ingredient databases (e.g. CosIng, EWG). LabelCheck does not provide certified medical diagnoses, clinical allergy testing, or formal regulatory product approvals. Consult a qualified dermatologist or medical practitioner for clinical advice.
          </div>
        </div>

        <div className="mt-8 flex flex-col sm:flex-row items-center justify-between text-xs text-slate-500 border-t border-slate-800/60 pt-6">
          <p>© {new Date().getFullYear()} LabelCheck Inc. College Minor Project Deliverable.</p>
          <p className="mt-2 sm:mt-0">Built with React, TypeScript, Vite & Tailwind CSS.</p>
        </div>
      </div>
    </footer>
  );
};
