import { 
  User, 
  SafetyReport, 
  Scan, 
  MasterIngredient, 
  MasterAllergen, 
  MasterHazard, 
  AlternativeProduct, 
  NotificationItem, 
  AdminStats, 
  AuditLog, 
  DatasetImport 
} from '../types';

export const initialMockUser: User = {
  id: 'user_101',
  fullName: 'Alex Morgan',
  email: 'alex.morgan@example.com',
  role: 'user',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
  createdAt: '2026-01-15T09:30:00Z',
  profile: {
    ageGroup: '25-34',
    allergies: ['Fragrance / Parfums', 'Formaldehyde', 'Methylisothiazolinone (MI)', 'Nickel'],
    skinType: 'sensitive',
    skinSensitivities: ['Eczema-prone', 'Rosacea flares', 'Contact Dermatitis'],
    avoidIngredients: ['Parabens', 'Phthalates', 'Sodium Lauryl Sulfate (SLS)', 'Oxybenzone'],
    dietaryRestrictions: ['Vegan', 'Gluten-Free Cosmetics'],
    fragranceSensitivity: true,
    preferredCategories: ['Skincare', 'Haircare', 'Sunscreen', 'Baby Care'],
    isOnboardingCompleted: true,
  },
};

export const initialMasterIngredients: MasterIngredient[] = [
  {
    id: 'ing_1',
    name: 'Methylparaben',
    casNumber: '99-76-3',
    category: 'Preservative',
    riskLevel: 'moderate',
    description: 'A synthetic antimicrobial preservative commonly used in cosmetic formulations. Identified as a potential endocrine-disrupting compound in certain studies.',
    isAllergen: false,
    isIrritant: true,
    isHazardous: true,
    ewgScore: 4,
    synonyms: ['Methyl 4-hydroxybenzoate', 'E218'],
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'ing_2',
    name: 'Fragrance / Parfum',
    casNumber: 'N/A',
    category: 'Fragrance Blend',
    riskLevel: 'high',
    description: 'An undisclosed mixture of aroma chemicals and synthetic fixatives. High likelihood of causing allergic contact dermatitis and sensitivity in reactive skin.',
    isAllergen: true,
    isIrritant: true,
    isHazardous: false,
    ewgScore: 8,
    synonyms: ['Aroma', 'Perfume', 'Essential Oil Blend'],
    updatedAt: '2026-02-05T11:20:00Z',
  },
  {
    id: 'ing_3',
    name: 'Sodium Lauryl Sulfate (SLS)',
    casNumber: '151-21-3',
    category: 'Surfactant / Cleanser',
    riskLevel: 'moderate',
    description: 'A harsh anionic detergent and foaming agent known to strip skin lipid barriers, leading to dryness and transepidermal water loss.',
    isAllergen: false,
    isIrritant: true,
    isHazardous: false,
    ewgScore: 3,
    synonyms: ['SLS', 'Sodium Dodecyl Sulfate'],
    updatedAt: '2026-02-10T14:15:00Z',
  },
  {
    id: 'ing_4',
    name: 'DMDM Hydantoin',
    casNumber: '6440-58-0',
    category: 'Formaldehyde Releaser',
    riskLevel: 'hazardous',
    description: 'A antimicrobial preservative that slowly releases formaldehyde over time to prevent microbial growth. Strong sensitizer associated with immunotoxicity.',
    isAllergen: true,
    isIrritant: true,
    isHazardous: true,
    ewgScore: 7,
    synonyms: ['1,3-Bis(hydroxymethyl)-5,5-dimethylimidazolidine-2,4-dione'],
    updatedAt: '2026-03-01T08:45:00Z',
  },
  {
    id: 'ing_5',
    name: 'Glycerin',
    casNumber: '56-81-5',
    category: 'Humectant',
    riskLevel: 'low',
    description: 'A naturally derived bio-compatible skin hydrator that attracts moisture to the stratum corneum.',
    isAllergen: false,
    isIrritant: false,
    isHazardous: false,
    ewgScore: 1,
    synonyms: ['Glycerol'],
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'ing_6',
    name: 'Ceramide NP',
    casNumber: '100403-19-8',
    category: 'Skin Replenisher',
    riskLevel: 'low',
    description: 'A natural lipid molecule identical to epidermal ceramide 3, supporting skin barrier recovery and moisture retention.',
    isAllergen: false,
    isIrritant: false,
    isHazardous: false,
    ewgScore: 1,
    synonyms: ['Ceramide 3'],
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'ing_7',
    name: 'Oxybenzone',
    casNumber: '131-57-7',
    category: 'UV Filter',
    riskLevel: 'hazardous',
    description: 'A chemical solar filter absorbed systemic through skin. Associated with hormonal disruption and coral reef bleaching toxicity.',
    isAllergen: true,
    isIrritant: true,
    isHazardous: true,
    ewgScore: 8,
    synonyms: ['Benzophenone-3'],
    updatedAt: '2026-03-05T16:00:00Z',
  },
  {
    id: 'ing_8',
    name: 'Phenoxyethanol',
    casNumber: '122-99-6',
    category: 'Preservative',
    riskLevel: 'low',
    description: 'A widely used glycol ether preservative. Generally well tolerated at Concentrations below 1%, though high doses may irritate eye tissues.',
    isAllergen: false,
    isIrritant: false,
    isHazardous: false,
    ewgScore: 2,
    synonyms: ['2-Phenoxyethanol'],
    updatedAt: '2026-01-15T12:00:00Z',
  },
];

export const initialMasterAllergens: MasterAllergen[] = [
  {
    id: 'alg_1',
    name: 'Fragrance / Parfum',
    severity: 'severe',
    commonProducts: ['Lotions', 'Shampoos', 'Perfumes', 'Deodorants'],
    description: 'Top cause of cosmetic contact allergy worldwide.',
  },
  {
    id: 'alg_2',
    name: 'Methylisothiazolinone (MI)',
    severity: 'severe',
    commonProducts: ['Wipes', 'Liquid Soaps', 'Conditioners'],
    description: 'Potent sensitizing preservative commonly causing facial eczema.',
  },
  {
    id: 'alg_3',
    name: 'Formaldehyde & Releasers',
    severity: 'severe',
    commonProducts: ['Nail Polish', 'Hair Straighteners', 'Body Wash'],
    description: 'Causes blistering rashes and systemic respiratory irritation in sensitive individuals.',
  },
  {
    id: 'alg_4',
    name: 'Linalool & Limonene (Oxidized)',
    severity: 'moderate',
    commonProducts: ['Essential Oils', 'Natural Creams', 'Serums'],
    description: 'Terpenes that form allergenic hydroperoxides when exposed to air.',
  },
];

export const initialMasterHazards: MasterHazard[] = [
  {
    id: 'haz_1',
    chemicalName: 'DMDM Hydantoin / Formaldehyde',
    casNumber: '6440-58-0',
    hazardCategory: 'Carcinogen & Immunotoxin',
    regulatoryStatus: 'Restricted in EU (< 0.05% free formaldehyde)',
    summary: 'Classified as a known human carcinogen by IARC when inhaled; severe topical sensitizer.',
  },
  {
    id: 'haz_2',
    chemicalName: 'Dibutyl Phthalate (DBP)',
    casNumber: '84-74-2',
    hazardCategory: 'Endocrine Disruptor & Reproductive Hazard',
    regulatoryStatus: 'Banned in cosmetics in EU & California Prop 65 listed',
    summary: 'Interferes with testosterone synthesis and thyroid hormone homeostasis.',
  },
  {
    id: 'haz_3',
    chemicalName: 'Oxybenzone (Benzophenone-3)',
    casNumber: '131-57-7',
    hazardCategory: 'Endocrine & Environmental Hazard',
    regulatoryStatus: 'Banned in Hawaii & US Virgin Islands due to reef ecotoxicity',
    summary: 'Exhibits estrogenic and anti-androgenic hormonal activity.',
  },
];

export const initialAlternatives: AlternativeProduct[] = [
  {
    id: 'alt_1',
    name: 'PureBarrier Barrier Repair Cream',
    brand: 'DermoCleanse',
    category: 'Moisturizer',
    imageUrl: 'https://images.unsplash.com/photo-1608248597260-843818e61230?auto=format&fit=crop&w=400&q=80',
    safetyScore: 96,
    reasonSuggested: 'Fragrance-free, zero parabens, zero formaldehyde releasers. Contains skin-identical Ceramides.',
    avoidedConcerns: ['Fragrance / Parfum', 'Methylparaben', 'DMDM Hydantoin'],
    rating: 4.9,
  },
  {
    id: 'alt_2',
    name: 'GentleHydrate Gentle Cleansing Gel',
    brand: 'BotanicalPure',
    category: 'Face Wash',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80',
    safetyScore: 94,
    reasonSuggested: 'Formulated with mild Coco-Glucoside instead of harsh Sodium Lauryl Sulfate.',
    avoidedConcerns: ['Sodium Lauryl Sulfate (SLS)', 'Fragrance / Parfum'],
    rating: 4.8,
  },
  {
    id: 'alt_3',
    name: 'MineralShield SPF 50 Broad Spectrum',
    brand: 'SafeSun Bio',
    category: 'Sunscreen',
    imageUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=400&q=80',
    safetyScore: 98,
    reasonSuggested: 'Uses non-nano Zinc Oxide rather than chemical Oxybenzone UV filters.',
    avoidedConcerns: ['Oxybenzone', 'Octinoxate', 'Synthetic Fragrance'],
    rating: 4.9,
  }
];

export const sampleScans: Scan[] = [
  {
    id: 'scan_001',
    userId: 'user_101',
    productName: 'Hydrating Daily Body Lotion',
    brand: 'VelvetGlow',
    category: 'Skincare',
    imageUrl: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=500&q=80',
    scanDate: '2026-09-14T14:20:00Z',
    score: 42,
    riskLabel: 'Higher Detected Risk',
    allergensCount: 2,
    hazardsCount: 1,
    status: 'completed',
    reportId: 'rep_001',
  },
  {
    id: 'scan_002',
    userId: 'user_101',
    productName: 'Ultra Gentle Facial Cleanser',
    brand: 'DermoCleanse',
    category: 'Face Wash',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=500&q=80',
    scanDate: '2026-09-12T11:00:00Z',
    score: 94,
    riskLabel: 'Lower Detected Risk',
    allergensCount: 0,
    hazardsCount: 0,
    status: 'completed',
    reportId: 'rep_002',
  },
  {
    id: 'scan_003',
    userId: 'user_101',
    productName: 'Beach Shield SPF 30 Sunscreen',
    brand: 'SunGlow Active',
    category: 'Sunscreen',
    imageUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=500&q=80',
    scanDate: '2026-09-08T09:15:00Z',
    score: 55,
    riskLabel: 'Higher Detected Risk',
    allergensCount: 1,
    hazardsCount: 1,
    status: 'completed',
    reportId: 'rep_003',
  },
];

export const sampleSafetyReport: SafetyReport = {
  id: 'rep_001',
  scanId: 'scan_001',
  productName: 'Hydrating Daily Body Lotion',
  brand: 'VelvetGlow',
  category: 'Body Care',
  imageUrl: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=600&q=80',
  scanDate: '2026-09-14T14:20:00Z',
  score: 42,
  riskLabel: 'Higher Detected Risk',
  riskExplanation: 'Analysis detected 2 known allergens matching your saved profile, 1 potential formaldehyde-releasing chemical hazard (DMDM Hydantoin), and synthetic preservatives that may cause contact dermatitis.',
  summaryCounts: {
    total: 8,
    allergens: 2,
    irritants: 3,
    hazards: 1,
    reviewNeeded: 1,
    unknown: 1,
  },
  personalizedWarnings: [
    'Contains "Fragrance / Parfum" which is listed in your profile allergies.',
    'Contains "DMDM Hydantoin" (Formaldehyde Releaser) which matches your allergy watch list.',
    'Formulated with Sodium Lauryl Sulfate which may exacerbate your sensitive eczema-prone skin.'
  ],
  ingredients: [
    {
      id: 'rpt_ing_1',
      rawName: 'Aqua (Water)',
      matchedName: 'Water / Aqua',
      category: 'Solvent',
      riskLevel: 'low',
      isAllergen: false,
      isIrritant: false,
      isHazardous: false,
      confidence: 0.99,
      personalizedMatch: false,
      userAvoidMatch: false,
      datasetReference: 'CosIng Database Standard',
    },
    {
      id: 'rpt_ing_2',
      rawName: 'Glycerin',
      matchedName: 'Glycerin',
      category: 'Humectant',
      riskLevel: 'low',
      isAllergen: false,
      isIrritant: false,
      isHazardous: false,
      confidence: 0.98,
      personalizedMatch: false,
      userAvoidMatch: false,
      datasetReference: 'EWG Skin Deep Score 1',
    },
    {
      id: 'rpt_ing_3',
      rawName: 'Parfum / Fragrance',
      matchedName: 'Fragrance / Parfum',
      category: 'Fragrance Blend',
      riskLevel: 'high',
      isAllergen: true,
      isIrritant: true,
      isHazardous: false,
      hazardDetails: 'Undisclosed synthetic perfume compounds',
      allergenDetails: 'High sensitization risk for contact dermatitis',
      confidence: 0.96,
      personalizedMatch: true,
      userAvoidMatch: true,
      whyFlagged: 'Matches User Profile Allergen: "Fragrance / Parfums"',
      datasetReference: 'EU Cosmetic Regulation Allergen List',
    },
    {
      id: 'rpt_ing_4',
      rawName: 'Sodium Lauryl Sulfate',
      matchedName: 'Sodium Lauryl Sulfate (SLS)',
      category: 'Surfactant / Cleanser',
      riskLevel: 'moderate',
      isAllergen: false,
      isIrritant: true,
      isHazardous: false,
      irritantDetails: 'Strips epidermal lipids causing dryness and barrier damage',
      confidence: 0.95,
      personalizedMatch: true,
      userAvoidMatch: true,
      whyFlagged: 'Matches User Profile Avoid List: "Sodium Lauryl Sulfate (SLS)"',
      datasetReference: 'CIR Expert Panel Report 2021',
    },
    {
      id: 'rpt_ing_5',
      rawName: 'DMDM Hydantoin',
      matchedName: 'DMDM Hydantoin',
      category: 'Formaldehyde Releaser',
      riskLevel: 'hazardous',
      isAllergen: true,
      isIrritant: true,
      isHazardous: true,
      hazardDetails: 'Slowly releases toxic formaldehyde over product shelf-life',
      allergenDetails: 'Triggers allergic skin reactions and immune sensitivity',
      confidence: 0.94,
      personalizedMatch: true,
      userAvoidMatch: true,
      whyFlagged: 'Hazardous Formaldehyde-releasing preservative',
      datasetReference: 'IARC Carcinogen Registry & EWG Score 7',
    },
    {
      id: 'rpt_ing_6',
      rawName: 'Methylparaben',
      matchedName: 'Methylparaben',
      category: 'Preservative',
      riskLevel: 'moderate',
      isAllergen: false,
      isIrritant: true,
      isHazardous: true,
      hazardDetails: 'Weak estrogenic endocrine activity in vitro',
      confidence: 0.97,
      personalizedMatch: true,
      userAvoidMatch: true,
      whyFlagged: 'Matches User Profile Avoid List: "Parabens"',
      datasetReference: 'EU Scientific Committee on Consumer Safety (SCCS)',
    },
    {
      id: 'rpt_ing_7',
      rawName: 'Tocopheryl Acetate',
      matchedName: 'Tocopheryl Acetate (Vitamin E)',
      category: 'Antioxidant',
      riskLevel: 'low',
      isAllergen: false,
      isIrritant: false,
      isHazardous: false,
      confidence: 0.92,
      personalizedMatch: false,
      userAvoidMatch: false,
      datasetReference: 'CosIng Database',
    },
    {
      id: 'rpt_ing_8',
      rawName: 'Botanical Ext 402X',
      matchedName: 'Unrecognized Extract 402X',
      category: 'Unknown',
      riskLevel: 'unknown',
      isAllergen: false,
      isIrritant: false,
      isHazardous: false,
      confidence: 0.55,
      personalizedMatch: false,
      userAvoidMatch: false,
      whyFlagged: 'Low OCR confidence. Requires manual verification.',
      datasetReference: 'Pending AI Taxonomy Review',
    },
  ],
  saferAlternatives: initialAlternatives,
  isFavorite: false,
};

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif_1',
    title: 'Scan Processing Complete',
    message: 'Your scan for "Hydrating Daily Body Lotion" has been analyzed. 2 allergens flagged.',
    type: 'warning',
    createdAt: '2026-09-14T14:21:00Z',
    read: false,
    link: '/report/rep_001',
  },
  {
    id: 'notif_2',
    title: 'New Ingredient Database Update',
    message: 'LabelCheck AI matched 14 new hazardous chemicals from the 2026 EU CosIng safety update.',
    type: 'info',
    createdAt: '2026-09-10T08:00:00Z',
    read: true,
  },
  {
    id: 'notif_3',
    title: 'Safer Alternative Found',
    message: 'A 98/100 rated safer alternative for your recent Sunscreen scan is now available.',
    type: 'success',
    createdAt: '2026-09-08T10:00:00Z',
    read: true,
    link: '/saved',
  }
];

export const initialAdminStats: AdminStats = {
  totalUsers: 1420,
  totalScans: 8940,
  totalIngredients: 4850,
  flaggedIngredientsCount: 620,
  recentScansTrend: [
    { date: 'Sep 10', scans: 240, hazardsDetected: 35 },
    { date: 'Sep 11', scans: 310, hazardsDetected: 42 },
    { date: 'Sep 12', scans: 290, hazardsDetected: 38 },
    { date: 'Sep 13', scans: 410, hazardsDetected: 62 },
    { date: 'Sep 14', scans: 380, hazardsDetected: 51 },
    { date: 'Sep 15', scans: 520, hazardsDetected: 78 },
    { date: 'Sep 16', scans: 460, hazardsDetected: 64 },
  ],
  topFlaggedChemicals: [
    { name: 'Fragrance / Parfum', count: 1840 },
    { name: 'Methylparaben', count: 920 },
    { name: 'DMDM Hydantoin', count: 640 },
    { name: 'Sodium Lauryl Sulfate', count: 580 },
    { name: 'Oxybenzone', count: 410 },
  ],
};

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log_1',
    action: 'Ingredient Rule Update',
    performedBy: 'Dr. Elena Vance (Admin)',
    role: 'admin',
    timestamp: '2026-09-16T12:00:00Z',
    details: 'Updated risk level for Oxybenzone from Moderate to Hazardous (EWG Score 8).',
  },
  {
    id: 'log_2',
    action: 'Dataset Batch Import',
    performedBy: 'System Auto Sync',
    role: 'admin',
    timestamp: '2026-09-15T04:00:00Z',
    details: 'Imported 350 CosIng 2026 ingredient definitions via CSV dataset.',
  },
  {
    id: 'log_3',
    action: 'User OCR Correction Review',
    performedBy: 'Admin Moderator',
    role: 'admin',
    timestamp: '2026-09-14T18:30:00Z',
    details: 'Approved fuzzy match rule correction for "DMDM Hydantion" -> "DMDM Hydantoin".',
  },
];

export const initialDatasetImports: DatasetImport[] = [
  {
    id: 'ds_1',
    filename: 'EU_CosIng_Database_2026_v2.csv',
    recordCount: 3450,
    status: 'completed',
    importedAt: '2026-09-15T04:00:00Z',
  },
  {
    id: 'ds_2',
    filename: 'EWG_SkinDeep_Hazard_Mappings.json',
    recordCount: 1200,
    status: 'completed',
    importedAt: '2026-08-20T14:22:00Z',
  },
  {
    id: 'ds_3',
    filename: 'FDA_Color_Additives_Restrictions.csv',
    recordCount: 180,
    status: 'completed',
    importedAt: '2026-07-11T09:10:00Z',
  },
];
